# Use the official Python base image
FROM python:3.9

# Set the working directory inside the container
WORKDIR /app

# Copy the requirements.txt file into the container
COPY requirements.txt .

# Install the dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the application files into the container
COPY . .

# Expose the port that Streamlit runs on
EXPOSE 8501

# Set the entry point for the container
ENTRYPOINT ["streamlit", "run", "app.py", "--server.port", "8501", "--server.ip", "0.0.0.0"]
